artifacts_root: artifacts

data_ingestion:
    root_dir: artifacts/data_ingestion
    source_URL1: https://github.com/Juicibox/dat/raw/refs/heads/main/benign.zip
    source_URL2: https://github.com/Juicibox/dat/raw/refs/heads/main/malignant.zip
    local_data_file1: artifacts/data_ingestion/data.zip
    local_data_file2: artifacts/data_ingestion/data2.zip
    unzip_dir: artifacts/data_ingestion 


prepare_base_model:
    root_dir: artifacts/prepare_base_model
    base_model_path: artifacts/prepare_base_model/base_model.h5
    updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5